/**:
  ros__parameters: # ALL GUESS
    min_longitudinal_offset: 1.8
    max_longitudinal_offset: 2.2 
    min_lateral_offset: -1
    max_lateral_offset: 1
    min_height_offset: 1.2
    max_height_offset: 2
