/**:
  ros__parameters:
    wheel_radius: 0.55 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.2 # GUESS--The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 2.56 # between front wheel center and rear wheel center
    wheel_tread: 1.4 # GUESS--between left wheel center and right wheel center
    front_overhang: 0.7 # GUESS--between front wheel center and vehicle front
    rear_overhang: 0.7 # GUESS--between rear wheel center and vehicle rear
    left_overhang: 0.1 # GUESS--between left wheel center and vehicle left
    right_overhang: 0.1 # GUESS--between right wheel center and vehicle right
    vehicle_height: 2.58 
    max_steer_angle: 0.70 # [rad]
